# Generated by Django 4.1.4 on 2022-12-22 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("KpoApplication", "0002_courses_exercise_course"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courses",
            options={"verbose_name": "Курс", "verbose_name_plural": "Курсы"},
        ),
        migrations.AddField(
            model_name="courses",
            name="number_of_course",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="completedtasks",
            name="correct",
            field=models.BooleanField(default=False, verbose_name="Правильность выполнения"),
        ),
        migrations.AlterField(
            model_name="courses",
            name="difficulty",
            field=models.CharField(
                choices=[("EASY", "Простая"), ("MEDIUM", "Средняя"), ("HARD", "Сложная")],
                default=None,
                max_length=255,
                verbose_name="Сложность",
            ),
        ),
        migrations.AlterField(
            model_name="courses",
            name="text",
            field=models.TextField(max_length=1000, verbose_name="Текст"),
        ),
        migrations.AlterField(
            model_name="courses",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Загловок"),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="course",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="KpoApplication.courses",
                verbose_name="Курс",
            ),
        ),
    ]
