# Generated by Django 4.1.4 on 2022-12-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("KpoApplication", "0003_alter_courses_options_courses_number_of_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="exercises",
            field=models.ManyToManyField(to="KpoApplication.exercise"),
        ),
        migrations.AlterField(
            model_name="courses",
            name="number_of_course",
            field=models.SmallIntegerField(blank=True, null=True, verbose_name="Номер курса"),
        ),
    ]
