# Generated by Django 4.1.4 on 2022-12-22 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("KpoApplication", "0004_courses_exercises_alter_courses_number_of_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courses",
            name="exercises",
        ),
    ]
