# Generated by Django 4.1.4 on 2022-12-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("KpoApplication", "0006_block_exercise_block"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="block",
        ),
        migrations.AlterField(
            model_name="block",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Название блока"),
        ),
    ]
