# Generated by Django 4.1.4 on 2022-12-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("KpoApplication", "0009_block_exercise_block"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="number_of_block",
            field=models.SmallIntegerField(
                blank=True, null=True, verbose_name="Номер блока"
            ),
        ),
    ]
