# Generated by Django 4.1.4 on 2022-12-24 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("KpoApplication", "0011_block_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="blocks",
            field=models.ManyToManyField(
                to="KpoApplication.block", verbose_name="Блоки"
            ),
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Доп.пользователь",
                "verbose_name_plural": "Доп.пользователи",
            },
        ),
    ]
