# Generated by Django 4.1.4 on 2022-12-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("KpoApplication", "0012_courses_blocks_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="first",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="block",
            name="number_of_block",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Номер блока"
            ),
        ),
    ]
