# Generated by Django 4.1.4 on 2022-12-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("KpoApplication", "0013_block_first_alter_block_number_of_block"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercise",
            old_name="block",
            new_name="blocks",
        ),
        migrations.AddField(
            model_name="block",
            name="ex",
            field=models.ManyToManyField(
                to="KpoApplication.exercise", verbose_name="Задачи в блоке"
            ),
        ),
    ]
