# Generated by Django 4.1.4 on 2022-12-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("KpoApplication", "0016_rename_block_exercise_blocks_block_ex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="ex",
            field=models.ManyToManyField(to="KpoApplication.exercise"),
        ),
    ]
