# Generated by Django 4.1.4 on 2022-12-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("KpoApplication", "0017_alter_block_ex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="ex",
            field=models.ManyToManyField(
                blank=True, null=True, to="KpoApplication.exercise"
            ),
        ),
    ]
