# Generated by Django 4.1.4 on 2022-12-25 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("KpoApplication", "0018_alter_block_ex"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="KpoApplication.courses",
            ),
        ),
    ]
