# Generated by Django 4.1.4 on 2022-12-25 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("KpoApplication", "0019_users_course"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="course",
            new_name="current_course",
        ),
    ]
