# Generated by Django 4.1.4 on 2022-12-25 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("KpoApplication", "0020_rename_course_users_current_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="block",
            name="first",
        ),
    ]
