# Generated by Django 4.1.4 on 2022-12-25 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("KpoApplication", "0024_favoritescourses"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FavoritesCourses",
        ),
    ]
